# Generated by Django 6.0.6 on 2026-07-07 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentchunk',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='book',
            name='metadata_schema',
        ),
        migrations.RemoveField(
            model_name='contentchunk',
            name='metadata',
        ),
        migrations.CreateModel(
            name='BookNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(help_text="e.g., 'Skandh', 'Chapter', 'Kand'", max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='content.book')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.booknode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='node',
            field=models.ForeignKey(blank=True, help_text='Deepest node this chunk belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.booknode'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
