# Generated by Django 6.0.6 on 2026-07-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contentchunk_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentchunk',
            name='chunk_type',
            field=models.CharField(choices=[('VERSE', 'Verse (Shloka/Mantra)'), ('TRANS', 'Translation'), ('EXPL', 'Explanation (Bhavarth/Commentary)'), ('PARA', 'Paragraph'), ('FOOT', 'Footnote'), ('HEAD', 'Heading')], default='PARA', max_length=5),
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='is_markdown_format',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='language',
            field=models.CharField(blank=True, choices=[('HI', 'Hindi'), ('SA', 'Sanskrit'), ('EN', 'English'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='markdown_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store formatting like spacing, alignment, or footnote markers here.'),
        ),
    ]
